### PR TITLE
Add `FreeformValidator` abstract class

### PR DESCRIPTION
**Pull request by dlh01**
## Summary

As titled.

## Notes for reviewers

None.

### Added

- `FreeformValidator` abstract class.

### CODE REVIEW

**Review by joemcgill — APPROVED** [review]
👍🏻 This looks good to me. I wonder if it would be useful to abstract these reusable methods into a trait that could be incorporated into private validators?

**Comment by dlh01** [comment]
@joemcgill Sorry, which methods in particular?

**Comment by joemcgill** [comment]
Ah sorry, the implementation that is tied up in the `FreeformValidator` could included in other validator classes via a trait rather than extending an abstract class, though maybe it doesn't really make a difference unless there is a valid use case to add that trait to something that would prefer to not extend the `FreeformValidator` class.

**Comment by dlh01** [comment]
Got it. I guess I wouldn't be necessarily opposed, but I think I'd have the same initial reaction: What would be the use case? If someone wants a class to be able to satisfy the interface using these same methods but isn't in a position to extend the abstract class, I would wonder whether the target class is doing too much.

**Pull request merged**
